config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cats
  resources :cat_rental_requests, only: [:new,:create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new,:create, :show]

  resource :session, only: [:new,:create, :destroy]


  root to: redirect('/cats')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
require 'date'

class Cat < ApplicationRecord
    COAT_COLOR=%w(black white tuxeto mixed orange ginger grey)

    validates :name, :user_id, :birth_date, :description, :sex, :color, presence: true
    validates :name, uniqueness: true
    validates :sex, inclusion: { in: ['F','M']}
    validates :sex, length: { is: 1}
    validates :color, inclusion: { in: COAT_COLOR}

    has_many :cat_rental_requests,
        class_name: :CatRentalRequests,
        primary_key: :id,
        foreign_key: :cat_id,
        dependent: :destroy

    belongs_to :owner,
        class_name: :User,
        primary_key: :id,
        foreign_key: :user_id

    def age
        #substracting two time gives the difference in seconds, then divide by how many seconds is in a year and flooring it
        return age=((Time.now - birth_date.to_time)/1.year.seconds).floor
    end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
    STATUS= %w(PENDING APPROVED DENIED)
    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: STATUS
    validate :does_not_overlap_approved_request

    belongs_to :cat,
        class_name: :Cat,
        primary_key: :id,
        foreign_key: :cat_id

    def overlapping_requests
        CatRentalRequest.where.not(id: self.id).where(cat_id: cat_id).where.not("start_date > :end_date OR end_date < :start_date",start_date: start_date, end_date: end_date)
    end

    def overlapping_approved_requests
       overlapping_requests.where("status= \'APPROVED\'") 
    end

    def overlapping_pending_requests
        overlapping_requests.where("status=\'PENDING\'")
    end

    def approve!
            self.status="APPROVED"
            self.save!
            overlapping_pending_requests.each do |request|
                request.deny!
            end
    end

    def deny!
        self.status="DENIED"
        self.save!
    end

    def pending?
        self.status=="PENDING"
    end

    def does_not_overlap_approved_request
        if (self.status=="APPROVED"||self.status=="PENDING") && overlapping_approved_requests.exists?
            errors[:base]<<'overlapping request'
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    attr_reader :password

    validates :username, :session_token, presence: true
    validates :password_digest, presence: {message: 'Password can\'t be blank'}
    validates :username, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}
    validates :session_token, presence: true
    after_initialize :ensure_session_token

    has_many :cats,
        class_name: :Cat,
        primary_key: :id,
        foreign_key: :user_id


    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
    end
    
    def is_password?(password)
        @password = password
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end
    
    def self.find_by_credentials(username,password)
        user= User.find_by(username: username)
        return nil if user.nil?
        user.is_password?(password) ? user :nil
    end


    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token
    end

    private
    def ensure_session_token
        self.session_token ||=self.class.generate_session_token
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def login!(user)
        @current_user = user
        session[:session_token]=user.session_token
    end

    def logout!
        current_user.try(:reset_session_token!)
        session[:session_token]=nil
    end

    def current_user
        return nil if session[:session_token].nil?
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_current_user!
        redirect_to new_session_url if current_user.nil?
    end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
    def approve
        current_request.approve!
        redirect_to cat_url(current_cat)
      end

    def deny
        current_request.deny!
        redirect_to cat_url(current_cat)
    end


    def new
        @request=CatRentalRequest.new
        render :new
    end

    def create
        @request=CatRentalRequest.new(requests_params)
        if @request.save
            redirect_to cat_url(@request.cat)
        else
            render :new
        end
    end

    private
    def current_request
        @request ||=
          CatRentalRequest.includes(:cat).find(params[:id])
    end
    
    def current_cat
        current_request.cat
    end

    def requests_params
        params.require(:request).permit(:cat_id,:start_date,:end_date)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    before_action :require_user!, only: %i(new create edit update)

    def index
        @cats=Cat.all

        render :index
    end

    def show
        @cat=Cat.find_by(id: params[:id])
        
        if @cat
            render :show
        else
            redirect_to cats_url
        end
    end

    def new
        @cat=Cat.new
        render :new
    end

    def create
        @cat = current_user.cats.new(cat_params)
        #@cat=Cat.new(cats_params)
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render :new
        end
    end

    def edit
        @cat = Cat.find_by(id: params[:id])
        render :edit
    end

    def update
        @cat=Cat.find_by(id: params[:id])
        if @cat.update(cats_params)
            redirect_to(@cat)
        else
            render :edit
        end
    end

    private
    def cats_params
        params.require(:cat).permit(:name,:color,:birth_date,:description,:sex)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user=User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )

        if user.nil?
            render json: 'Credentials were wrong'
        else
            login!(user)
            redirect_to user_url(user)
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_current_user!, except: [:create, :new]
    
    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            render json:@user.errors.full_messages
        end
    end

    def new
        @user = User.new
    end

    def show
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/index.html.erb
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

</style>

<h1>Requests</h1>
<table>
    
        <tr>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Cat ID</th>
        </tr>
    

    <% @requests.each do |request|%>
    <tr>
        <td><%= request.start_date %> </td>
        <td><%= request.end_date %> </td>
        <td><%= request.cat_id %> </td>
    </tr>
    <% end %>
    
</table>

app/views/cat_rental_requests/new.html.erb
<h1>Cat Rental Request</h1>
<form action="<%= cat_rental_requests_url%>" method="post">
    <label for="cat_id">Cat</label>
    <select id="cat_id" name="request[cat_id]">
        <option disabled selected>-- Please select a cat --</option>
        <% Cat.all.each do |cat|%>
        <option value="<%= cat.id %>"> <%= cat.name %>  </option>
        <% end %>
    </select>
    <br>
    <label for="start_date">Start Date </label>
    <input type="date" id="start_date" name="request[start_date]">
    <br>
    <label for="end_date">End Date </label>
    <input type="date" id="end_date" name="request[end_date]">
    <br>
    <input type="submit">
</form>

app/views/cat_rental_requests/show.html.erb
<h1>Requests</h1>
<table>
    
        <tr>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Cat ID</th>
        </tr>
    
    <tr>
        <td><%= @request.start_date %> </td>
        <td><%= @request.end_date %> </td>
        <td><%= @request.cat_id %> </td>
    </tr>
    
</table>

app/views/cats/_form.html.erb
<% if action==:edit %>
    <%action_url = cat_url(cat) %>
<% else%>
<% action_url = cats_url%>
<% end %>

<form action="<%= action_url%>" method="post">
<!-- if editing the form, we want to patch and prefill -->
    <% if action ==:edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="name">Name</label>
    <input id="name" type="text" name="cat[name]" value="<%= cat.name%>">
    <br>
    <label for="sex">Sex</label>
    <input type="radio" name="cat[sex]" value="M" <%= cat.sex =="M"? "checked": ""%> > Male
    <input type="radio" name="cat[sex]" value="F" <%= cat.sex =="F"? "checked": ""%> > Female
    <br>
    <label for="color">Coat Color</label>
    <select id="color" name="cat[color]">
        <option disabled selected>-- Please select a coat color --</option>
        <% Cat::COAT_COLOR.each do |color|%>
        <option value="<%= color %>" <%= cat.color == color ? "selected":""%>> <%= color %>  </option>
        <% end %>
    </select>
    <br>
    <label for="birth_date">Birth Date </label>
    <input type="date" id="birth_date" name="cat[birth_date]" value="<%=cat.birth_date%>">
    <br>
    <label for="description">Description</label>
    <textarea id="description" name="cat[description]"><%=cat.description%></textarea>
    <br>
    <input type="submit" value="<%= action ==:edit ? "Update Cat":"Add Cat"%>">
</form>

app/views/cats/edit.html.erb
<h1> Edit Cat </h1>

<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<style>

.cat {width: 25%;
    padding: 20px;
    margin: 20px 0;
    align-items: center;
    display: flex;
    justify-content: center;
    background-color: darkcyan;}
.cat-section {width:100%; display:flex;justify-content:space-around;flex-wrap:wrap;}
</style>

<h1>The Cats</h1>
<section class="cat-section">
<% @cats.each do |cat|%>
<div class="cat">
    <h2><%= link_to "#{cat.name}", cat%></h2>
</div>
<% end %>
</section>

app/views/cats/new.html.erb
<h1> Add New Cat </h1>

<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<h2>Information</h2>
<table>
    
        <tr>
            <th>Name</th>
            <th>Sex</th>
            <th>Age</th>
            <th>Color</th>
            <th>Description</th>
        </tr>
    
    <tr>
        <td><%= @cat.name %> </td>
        <td><%= @cat.sex %> </td>
        <td><%= @cat.age %> </td>
        <td><%= @cat.color %> </td>
        <td><%= @cat.description %> </td>
    </tr>
    
</table>
<a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %></a>

<h2>Requests</h2>
<table>
    
        <tr>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Status</th>
            <th>Approve / Deny </th>
        </tr>
    

    <% CatRentalRequest.where(cat_id: @cat.id).order(:start_date).each do |request|%>
    <tr>
        <td><%= request.start_date %> </td>
        <td><%= request.end_date %> </td>
        <td><%= request.status %> </td>
        <td>
        <% if request.pending?%>
        <form action="<%= approve_cat_rental_request_url(request)%>" method="post">
        <input type="submit" value="Approve">
        </form>
        <br>
        <form action="<%= deny_cat_rental_request_url(request)%>" method="post">
        <input type="submit" value="Deny">
        </form>
        <% end %>
        </td>
    </tr>
    <% end %>
    
</table>

<a href="<%= new_cat_rental_request_url %>">Add request </a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NineNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <div class='header'>
    <% if !current_user.nil? %>
    <ul>
      <li>Logged in as <%= current_user.username %></li>
      <li>
        <form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
        <input type="hidden" value="delete" name="_method" />
        <input type="submit" value= "Logout" />
        </form>
      </li>
    </ul>
    <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% action =(user.persisted? ? user_url(user) : users_url)%>
<% method = (user.persisted? ? "patch": "post")%>
<% message = (user.persisted? ? "Update user" : "Create user")%>

<form action="<%= action %>" method ="post">
    <input name="_method" type="hidden" value="<%= method %>">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    <label for="user_username">Username</label>
    <input id="user_username" name="user[username]" type="text">
    <br>
    <label for="user_password">Password</label>
    <input id="user_password" name="user[password]" type="password">
    <br>

    <input type="submit" value="<%= message %>"/>
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", user: @user%>

app/views/users/show.html.erb
<h1>User Page</h1>

<p> Hello, user!</p>